Update UserGuide.md with Patient Record commands
AY2122S1-CS2103-W14-1/tp pull request #18
Opened 2021-09-21 11:41 UTC by rish-16

This commit also updates Rish's person details for `AboutUs.md`.

2021-09-21 11:44 UTC, huyuxin0429 approved these changes
LGTN

2021-09-22 04:32 UTC, didymental commented on docs/UserGuide.md
> +Format: `create -p f/FIRST_NAME n/GIVEN_NAME m/[MEDICAL_HISTORY]`
Hi @rish-16, as communicated, let's keep to ```add``` being the command word: so ```add -p``` instead of ```create -p```

Thank you.

2021-09-22 04:33 UTC, didymental requested changes
Hi @rish-16, changes to do with the ```create``` keyword instead - we'll stick to ```add``` since it's already been built for us, so less refactoring needed. 

Thanks!

2021-09-22 09:05 UTC, rish-16 commented
Understood @didymental! Will make the changes to the guide.

2021-09-26 04:53 UTC, closed without merging